version: 1

# Enable or disable CodeRabbit
enabled: true

# Configure review settings
review:
  # Enable automatic reviews
  auto_review: true
  
  # Configure review scope
  scope:
    # Review all files
    all_files: true
    
    # Exclude certain directories
    exclude:
      - "node_modules/"
      - "dist/"
      - ".git/"
      - ".idea/"

# Configure comment settings
comments:
  # Enable inline comments
  inline: true
  
  # Enable summary comments
  summary: true

# Configure language-specific settings
languages:
  typescript:
    # Enable TypeScript-specific analysis
    enabled: true
    # Add TypeScript-specific rules
    rules:
      - name: "typescript-eslint"
        enabled: true
    
  javascript:
    # Enable JavaScript-specific analysis
    enabled: true
    # Add JavaScript-specific rules
    rules:
      - name: "javascript-eslint"
        enabled: true

# Add security scanning
security:
  enabled: true
  rules:
    - name: "dependency-check"
      enabled: true
    - name: "code-scanning"
      enabled: true 