[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# Handle SPA routing for React application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables examples - these should be set in Netlify UI for security
[context.production.environment]
  # VITE_AUTH0_DOMAIN = "Set in Netlify UI"
  # VITE_AUTH0_CLIENT_ID = "Set in Netlify UI"
  # VITE_AUTH0_AUDIENCE = "Set in Netlify UI" 