# Example of correct HTTP requests
GET http://localhost:5173/api/items

###

GET http://localhost:5173/api/item?id=99

###

# INCORRECT - This will cause a MalformedURLException
# GET http://useEffect(()=>

# CORRECT - Use a valid URL instead
# If you need to call an API from React, use fetch or axios inside a useEffect hook:
# 
# useEffect(() => {
#   fetch('http://localhost:5173/api/items')
#     .then(response => response.json())
#     .then(data => console.log(data));
# }, []);
