apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files-pvc
  namespace: vikunja
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo 