apiVersion: v1
kind: ServiceAccount
metadata:
  name: vikunja
  namespace: vikunja
  annotations:
    iam.gke.io/gcp-service-account: vikunja-prod@luknerlumina-firebase.iam.gserviceaccount.com
automountServiceAccountToken: true 