name: CodeRabbit

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master

jobs:
  coderabbit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: CodeRabbit Review
        uses: coderabbitai/coderabbit@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODERABBIT_TOKEN: ${{ secrets.CODERABBIT_TOKEN }} 