name: Tebra Security Check

on:
  push:
    branches:
      - main
      - master
      - 'feature/ehr-auth-data-retrieval'
  pull_request:
    branches:
      - main
      - master
      - 'feature/ehr-auth-data-retrieval'
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight

jobs:
  security-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to Google Cloud (WIF)
      id: auth-wif
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ vars.WIF_PROVIDER || '' }}
        service_account: ${{ vars.WIF_SERVICE_ACCOUNT || '' }}
      continue-on-error: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: luknerlumina-firebase

    - name: Configure gcloud
      run: |
        gcloud config set project luknerlumina-firebase
        
        # Check if WIF authentication worked
        if gcloud auth list --filter=status:ACTIVE --format="value(account)" | grep -q "@"; then
          echo "✅ Authentication successful"
        else
          echo "⚠️  No authentication configured - security checks may be limited"
        fi

    - name: Security Check with GSM
      run: |
        chmod +x ./tebra-tools/scripts/security-check-gsm.sh
        ./tebra-tools/scripts/security-check-gsm.sh
      continue-on-error: true