name: Tebra Security Check

on:
  push:
    branches: 
      - main
      - master
      - 'feature/ehr-auth-data-retrieval'
  pull_request:
    branches: 
      - main
      - master
      - 'feature/ehr-auth-data-retrieval'
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight

jobs:
  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set Project ID
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Security Check with GSM
      run: |
        chmod +x ./tebra-tools/scripts/security-check-gsm.sh
        ./tebra-tools/scripts/security-check-gsm.sh
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }} 